nodeLinker: node-modules

npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: 582ED04F-E782-4986-88B1-CCA9AC7F0118

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"

plugins:
  - .yarn/plugins/override-state.js

yarnPath: .yarn/releases/yarn-4.0.0-rc.28.cjs
