npmScopes:
  nodeLinker: 'pnp'
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 582ED04F-E782-4986-88B1-CCA9AC7F0118
    npmRegistryServer: 'https://npm.fontawesome.com/'

yarnPath: .yarn/releases/yarn-3.2.4.cjs
