yarnPath: .yarn/releases/yarn-3.2.4.cjs

nodeLinker: "node-modules"

plugins:
  - .yarn/plugins/override-state.js

npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: "582ED04F-E782-4986-88B1-CCA9AC7F0118"

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/