nodeLinker: node-modules

npmRegistries:
  //npm.fontawesome.com/:
    npmAuthToken: 582ED04F-E782-4986-88B1-CCA9AC7F0118

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com/'

supportedArchitectures:
  os:
    - 'linux'
  cpu:
    - 'x64'

yarnPath: .yarn/releases/yarn-4.0.0-rc.43.cjs
