--- 
jobs: 
  build_and_deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Install Node"
        uses: actions/setup-node@v3
        with: 
          node-version: 17.x
      -
        name: "Something1"
        run:  echo "nodeLinker: "node-modules"" >> .yarnrc.yml "
      - 
        name: "Install Yarn"
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      -
        name: "Something2"
        run:  sudo chown -R $USER:$USER /home/runner/work/dietasadrian/dietasadrian/node_modules
      - 
        name: "Checkout Repo"
        uses: actions/checkout@v3
      - 
        uses: FirebaseExtended/action-hosting-deploy@v0
        with: 
          channelId: live
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIETASADRIANBADILLAFIREBASE }}"
          projectId: dietasadrianbadillafirebase
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
name: "Deploy to Firebase Hosting on merge"
? "on"
: 
  push: 
    branches: 
      - main