name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Install Node"
        uses: actions/setup-node@v3
        with: 
          node-version: 17.x
      - 
        name: "Install Yarn"
        uses: borales/actions-yarn@v3.0.0
      
        run: yarn install && yarn build
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: dietasadrianbadillafirebase
          channelId: live