--- 
jobs: 
  build_and_deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Install Node"
        uses: actions/setup-node@v3
        with: 
          node-version: 17.x
      - 
        name: "Install Yarn"
        run: "curl -o- -L https://yarnpkg.com/install.sh | bash"
      - 
        name: "Checkout Repo"
        uses: actions/checkout@v3
      - 
        name: "Install Yarn 2"
        run: yarn set version berry
      - 
        name: "Install Functions Dependencies"
        run: yarn
      - 
        uses: FirebaseExtended/action-hosting-deploy@v0
        with: 
          channelId: live
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIETASADRIANBADILLAFIREBASE }}"
          projectId: dietasadrianbadillafirebase
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
name: "Deploy to Firebase Hosting on merge"
? "on"
: 
  push: 
    branches: 
      - main
