---
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: 'Install Node'
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: 'Yarn Install'
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: 'deleting node modules and lock'
        run: sudo rm -rf /home/runner/work/dietasadrian/dietasadrian/node_modules && sudo rm -rf /home/runner/work/dietasadrian/dietasadrian/yarn.lock

      - name: 'different form to install the modules'
        run: sudo yarn

      - name: 'Yarn Build'
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: 'chmod node modules'
        run: sudo chmod 777 -R /home/runner/work/dietasadrian/dietasadrian/node_modules

      - name: 'chmod node dist/apps/'
        run: sudo chmod 777 -R /home/runner/work/dietasadrian/dietasadrian/dist/

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIETASADRIANBADILLAFIREBASE }}'
          projectId: dietasadrianbadillafirebase
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
name: 'Deploy to Firebase Hosting on PR'
'on': pull_request
